name: Launcher Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  release:
    runs-on: self-hosted

    steps:
      ##Tag Number input
      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2

      ##ReleaseChannel - go!
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: sasaddLauncher - ${{ steps.get_version.outputs.version }}
          body: |
            ### ▼ご使用のOSのインストーラーをダウンロードしてください。
            [Windows](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/sasaddLauncher-setup-${{ steps.get_version.outputs.version-without-v }}.exe)
            [Mac OS X](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/sasaddLauncher-setup-${{ steps.get_version.outputs.version-without-v }}.dmg)
            [Linux](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/sasaddLauncher-setup-${{ steps.get_version.outputs.version-without-v }}.AppImage)

            ### ビルド情報
            ${{ steps.get_version.outputs.version }} by ${{ github.actor }}
          draft: false
          prerelease: false


  build:
    runs-on: ${{ matrix.os }}

    needs:
      - release

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
            node-version: '14'

      ##Tag Number input
      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2

      ##CreateAPP - yarn release
      - name: install yarn
        run : npm install -g yarn

      - name: patch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./sasaddLC p
        shell: bash

      - name: dist mac
        working-directory: sasaddLauncher
        if: matrix.os == 'macos-latest'
        run: yarn run dist:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: dist windows
        working-directory: sasaddLauncher
        if: matrix.os == 'windows-latest'
        run: yarn run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: dist linux
        working-directory: sasaddLauncher
        if: matrix.os == 'ubuntu-latest'
        run: yarn run dist:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

      ##ActionRelease - zip
      - uses: actions/upload-artifact@v1
        name: Action-Upload-MacOS1
        if: matrix.os == 'macos-latest'
        with:
          name: MacOs Release
          path: dist

      - uses: actions/upload-artifact@v1
        name: Action-Upload-Windows1
        if: matrix.os == 'windows-latest'
        with:
          name: Windows Release
          path: dist

      - uses: actions/upload-artifact@v1
        name: Action-Upload-Ubuntu1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Linux Release
          path: dist

      - uses: AButler/upload-release-assets@v2.0
        name: Upload Release File - MacOS1
        if: matrix.os == 'macos-latest'
        with:
          files: sasaddLauncher/dist/latest-mac.yml;dist/sasaddLauncher-setup-${{ steps.get_version.outputs.version-without-v }}.{dmg,dmg.blockmap}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.get_version.outputs.version }}

      - uses: AButler/upload-release-assets@v2.0
        name: Upload Release File - Windows1
        if: matrix.os == 'windows-latest'
        with:
          files: sasaddLauncher/dist/latest.yml;dist/sasaddLauncher-setup-${{ steps.get_version.outputs.version-without-v }}.{exe,exe.blockmap}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.get_version.outputs.version }}

      - uses: AButler/upload-release-assets@v2.0
        name: Upload Release File - Ubuntu1
        if: matrix.os == 'ubuntu-latest'
        with:
          files: sasaddLauncher/dist/latest-linux.yml;dist/sasaddLauncher-setup-${{ steps.get_version.outputs.version-without-v }}.AppImage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.get_version.outputs.version }}

  notification:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/setup-ruby@v1
      - name: Send Webhook Notification
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          git clone https://github.com/gorilla-devs/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
